### ISSUE TITLE
Sharing the split for partial training examples

### ISSUE THREAD

**Issue by mkimhi** [KainingYing/CTVIS#4]
Thank you for sharing the code,

Could you also share the data used for partial training examples (1%, 5% etc) for ytvis21?

The training script would also be appreciated!

thanks!

**Comment by KainingYing** [comment]
Hi @mkimhi, thanks for your attention.

We follow a similar way (MinVIS) to sample the partial video frames for ytvis21. 

For example, for the `1% setting`, we select 1% frames (at least one frame) from each video. 

Since MinVIS did not provide the corresponding training dataset, it is also very difficult for us to align MinVIS. You can use similar methods to generate locally partial datasets that you want.
